services:
  app_product:
    build: productService-V1
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_HOSTNAME: product_service   # Nombre del contenedor de MySQL
      DB_PORT: 3307                  # Puerto donde se expone MySQL
      DB_URL: jdbc:mysql://${DB_HOSTNAME}:${DB_PORT}/products?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER_NAME: root
      DB_PASSWORD: 127300
    depends_on:
      product_service:
        condition: service_healthy

  product_service:
    image: mysql:8.0.33 
    ports:
      - "3307:3306"
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: 127300
      MYSQL_PASSWORD: 127300
      MYSQL_DATABASE: products
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 10